---
- name: Prepare hosts
  hosts: all
  roles:
    - role: ansible-loki
      vars:
        loki_version: 2.6.0
  pre_tasks:
  - name: Install unzip
    package:
      disablerepo: epel
      name:
        - unzip
